### PR TITLE
utilities: fix few shadowed variables

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Fix a couple of:

settings_mgmt.c:414:30: warning: declaration of ‘ok’ shadows a previous local [-Wshadow]
  414 |                         bool ok;
      |                              ^~

### CODE REVIEW

**Review by JordanYates — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@JordanYates do you happen to have permissions to merge this and do the cherry pick dance as well? I sure don't.

**Review by JordanYates — CHANGES_REQUESTED** [review]
Whoops, didn't realise this was targeting the `zephyr` branch.
You should be able to make a PR directly targeting the `v4.6.0` branch.

**Comment by fabiobaltieri** [comment]
this is working great... let me try something

**Comment by JordanYates** [comment]
I think its because those 2 commits that appear have been modified between `zephyr` and `v4.6.0`. I suspect if you rebase the commit on your fork as well they will disappear.

**Comment by fabiobaltieri** [comment]
Just pulled and rebased on my client, they got skipped automatically, go figure.

**Review by JordanYates — APPROVED** [review]
So now the standard process of a PR in the zephyr repo to check the module PR should work fine.

**Comment by fabiobaltieri** [comment]
Running on https://github.com/zephyrproject-rtos/zephyr/pull/61947

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
