### PR TITLE
Merge back v4.6.0-zephyr, fix a shdow variable

### PR DESCRIPTION
**Pull request by fabiobaltieri**
This was supposed to be just a shadow variable fix, but it turns out that west.yaml currently points at a branch of this module rather than the main one (`zephyr`), so merge that back as well.

### CODE REVIEW

**Comment by JordanYates** [comment]
> This was supposed to be just a shadow variable fix, but it turns out that west.yaml currently points at a branch of this module rather than the main one (zephyr), so merge that back as well.

That is intentional. The original `zephyr` branch periodically had the latest upstream changed squashed in from what I remember. At some point, we decided to change that to a "branch per release" model, where we just re-cherry-pick our Zephyr commits on top of new releases, instead of updating the `zephyr` branch.

It makes reviewing how we have diverged from upstream much easier.

**Comment by JordanYates** [comment]
This PR should just contain your fixup commit IMO

**Comment by fabiobaltieri** [comment]
> That is intentional. The original `zephyr` branch periodically had the latest upstream changed squashed in from what I remember. At some point, we decided to change that to a "branch per release" model, where we just re-cherry-pick our Zephyr commits on top of new releases, instead of updating the `zephyr` branch.
> 
> It makes reviewing how we have diverged from upstream much easier.

Ok that explains what happened, but then if I'm reading it right https://github.com/zephyrproject-rtos/loramac-node/tree/v4.6.0-zephyr has been pushed directly (no PR and no review). Is that ok? The manifest PR obviously is reviewed normally, but I'm concerned about the process for this module being different than all of the others.

For instance we ask module contributors to open a manifest PR pointing at the PR so that the upstream CI can run, how does that work in that case? That would make no sense if the fixup has to be pushed on a different tree and someone else is going to cherry pick it down the road.

@carlescufi @nashif any opnion on this?

**Comment by JordanYates** [comment]
My understanding is that module maintainers are more or less free choose the model that works for them (not me for this module).

I don't see any conflict with what you are saying and how this can work anyway. Upstream is periodically pulled into whatever the upstream main branch is called. Make a branch called `zephyr-this-release` at whatever point. Open a PR with Zephyrs cherry-picked changes against that new branch.

**Comment by fabiobaltieri** [comment]
> I don't see any conflict with what you are saying and how this can work anyway. Upstream is periodically pulled into whatever the upstream main branch is called. Make a branch called `zephyr-this-release` at whatever point. Open a PR with Zephyrs cherry-picked changes against that new branch.

Not sure I follow, the process (https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules) asks the contributor to open a PR upstream pointing at the module one. Let's say I only include my change here... then what? I have to either open a second PR with the change rebased on top of the whatever branch and use that as a reference? Or create another branch on my local fork and change the manifest to point at that instead, adding a new remote in the manifest in the process?

**Comment by fabiobaltieri** [comment]
@JordanYates I opened https://github.com/zephyrproject-rtos/loramac-node/pull/13 as well with just that comment on the zephyr branch, at this stage I care more about fixing this (it's breaking the CI) than arguing about how to manage the repo but I think it should be dscussed as well.

**Pull request closed without merging**
