### PR TITLE
Update LoRaMac-node to 4.5.2

### PR DESCRIPTION
**Pull request by tagunil**
Update LoRaMac-node to the latest stable release.
Requires adaptation of the Zephyr glue code (https://github.com/zephyrproject-rtos/zephyr/pull/35892).

### CODE REVIEW

**Comment by Mani-Sadhasivam** [comment]
@tagunil Can you please get rid of the merge commit 275d9d0 and just rebase the upstream commits?

**Review by Mani-Sadhasivam — CHANGES_REQUESTED** [review]
Please get rid of the merge commit 275d9d0 and just rebase the upstream commits. Rest looks good!

**Comment by tagunil** [comment]
> Please get rid of the merge commit [275d9d0](https://github.com/zephyrproject-rtos/loramac-node/commit/275d9d0657172e436a8144df78755b6fa0cfb021) and just rebase the upstream commits. Rest looks good!

I can do that, of course, but that wouldn't be very trivial due to earlier cherry-picking like #10 and independent fixes like #8. Moreover, it would force us to rebase any further upstream commits. Wouldn't it be better to create a new default branch from the latest upstream release? It would diverge with the current default branch somewhere after 2d5b3f05f31c47ff0f06530c51727ab7e5fe2405. We could cherry-pick some of our stuff like a1f456bb53e88981a4352f24655d3525ce8f12f1 on top of that, and the rest (CMakeLists.txt-related) would go to the main Zephyr tree.

**Comment by tagunil** [comment]
@Mani-Sadhasivam, I can actually use my newfound collaborator status to create a new branch in this repo and demonstrate my proposal. Should I do that?

**Comment by Mani-Sadhasivam** [comment]
> > Please get rid of the merge commit [275d9d0](https://github.com/zephyrproject-rtos/loramac-node/commit/275d9d0657172e436a8144df78755b6fa0cfb021) and just rebase the upstream commits. Rest looks good!
> 
> I can do that, of course, but that wouldn't be very trivial due to earlier cherry-picking like #10 and independent fixes like #8. > Moreover, it would force us to rebase any further upstream commits. 

That's what we were doing before but...

> Wouldn't it be better to create a new default branch from the latest upstream release? It would diverge with the current default branch somewhere after [2d5b3f0](https://github.com/zephyrproject-rtos/loramac-node/commit/2d5b3f05f31c47ff0f06530c51727ab7e5fe2405).

Hmm, okay. It sounds like a good approach too but let's make sure we don't miss any commits (obviously).

> We could cherry-pick some of our stuff like [a1f456b](https://github.com/zephyrproject-rtos/loramac-node/commit/a1f456bb53e88981a4352f24655d3525ce8f12f1) on top of that, and the rest (CMakeLists.txt-related) would go to the main Zephyr tree.

a1f456b is not _our_ commit, it is merged into upstream repo and we cherry-picked it. So it should be there.

**Comment by Mani-Sadhasivam** [comment]
> @Mani-Sadhasivam, I can actually use my newfound collaborator status to create a new branch in this repo and demonstrate my proposal. Should I do that?

Not needed... Just fix the conflict and cherry-pick zephyr commits.

**Comment by tagunil** [comment]
> [a1f456b](https://github.com/zephyrproject-rtos/loramac-node/commit/a1f456bb53e88981a4352f24655d3525ce8f12f1) is not _our_ commit, it is merged into upstream repo and we cherry-picked it. So it should be there.

One less thing to worry about.

**Comment by tagunil** [comment]
> Not needed... Just fix the conflict and cherry-pick zephyr commits.

Now I'm quite confused about which way we are going. As far as I know, we could either create a new clean branch and cherry-pick our commits to it, or try to fix conflicts in this branch which already has our commits. If you have some third way in your mind, could you please explain that to me?

**Comment by Mani-Sadhasivam** [comment]
> > Not needed... Just fix the conflict and cherry-pick zephyr commits.
> 
> Now I'm quite confused about which way we are going. As far as I know, we could either create a new clean branch and cherry-pick our commits to it, or try to fix conflicts in this branch which already has our commits. If you have some third way in your mind, could you please explain that to me?

Sorry for the confusion. I meant to say the first option.

**Comment by tagunil** [comment]
I've created the new branch named `zephyr`. Further work moves to #11.

**Pull request merged**
