### PR TITLE
Add Zephyr-related changes on top of LoRaMac-node v4.5.2

### PR DESCRIPTION
**Pull request by tagunil**
This is the continuation of #9 in a new branch.
https://github.com/zephyrproject-rtos/zephyr/pull/35892 is also reworked to match the new structure.

### CODE REVIEW

**Review by JordanYates — APPROVED** [review]
Looks good to me, slightly unrelated but I think it makes sense for the `master` branch to be synced with the upstream `master`, as opposed to hanging around on the old `zephyr_v2.5` branch.

**Comment by tagunil** [comment]
> Looks good to me, slightly unrelated but I think it makes sense for the `master` branch to be synced with the upstream `master`, as opposed to hanging around on the old `zephyr_v2.5` branch.

It definitely makes sense, but it is not recommended according to https://docs.zephyrproject.org/latest/guides/modules.html
Maybe we should just remove the `master` branch.

**Review by Mani-Sadhasivam — APPROVED** [review]
Change looks good to me but I'm slightly worried about the authorship issue with 29e516e. I'd like @alexanderwachter to approve this PR since he authored 29e516e for SX1276. Otherwise, you can add a separate commit on top of his one for SX1272.

**Comment by Mani-Sadhasivam** [comment]
> Maybe we should just remove the master branch.

Yes, we should just use `zephyr` branch and backport branches. There shouldn't be a `master` branch,

**Comment by tagunil** [comment]
> Change looks good to me but I'm slightly worried about the authorship issue with [29e516e](https://github.com/zephyrproject-rtos/loramac-node/commit/29e516ec585b1a909af2b5f1c60d83e7d4d563e3). I'd like @alexanderwachter to approve this PR since he authored [29e516e](https://github.com/zephyrproject-rtos/loramac-node/commit/29e516ec585b1a909af2b5f1c60d83e7d4d563e3) for SX1276. Otherwise, you can add a separate commit on top of his one for SX1272.

Ah, I see. I've rearranged remaining differences from upstream into two new commits because I've considered these changes trivial, but I have no problem with splitting them back to restore authorship.

**Comment by alexanderwachter** [comment]
I don't have any problems with the authorship! Please go ahead with the easiest path for you.

**Comment by alexanderwachter** [comment]
I think my idea was to keep the master (should be main now) in sync with upstream, rebase and tag the zephyr branch if the version needs to be bumped. But I have no idea if that is the "zephyr way" to do it.

**Comment by tagunil** [comment]
I've added the Co-authored-by trailers to highlight @alexanderwachter's contribution to this part. @Mani-Sadhasivam, what else do we need to move forward?

**Pull request merged**
