### PR TITLE
Add LoRaWAN support for Zephyr

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
This PR rebases onto loramac-node master and also adds LoRaWAN support for Zephyr by enabling necessary drivers.

Signed-off-by: Manivannan Sadhasivam <mani@kernel.org>

### CODE REVIEW

**Comment by carlescufi** [comment]
@Mani-Sadhasivam is this required? Can you fix the title of the PR?

**Comment by Mani-Sadhasivam** [comment]
> @Mani-Sadhasivam is this required? Can you fix the title of the PR?

@carlescufi What do you mean by required? These drivers are required to enable LoRaWAN support. Also what's wrong with title?

**Comment by carlescufi** [comment]
> > @Mani-Sadhasivam is this required? Can you fix the title of the PR?
> 
> @carlescufi What do you mean by required? These drivers are required to enable LoRaWAN support. Also what's wrong with title?

OK I missed something here then. What is it that we are enabling when compared to what is already working in the tree today?

**Comment by Mani-Sadhasivam** [comment]
> > > @Mani-Sadhasivam is this required? Can you fix the title of the PR?
> > 
> > 
> > @carlescufi What do you mean by required? These drivers are required to enable LoRaWAN support. Also what's wrong with title?
> 
> OK I missed something here then. What is it that we are enabling when compared to what is already working in the tree today?

We need to enable few cryptographic drivers needed by the LoRaMAC stack. Please see the commit: https://github.com/zephyrproject-rtos/loramac-node/pull/3/commits/3e52b0bccc313f911e24bee15a256f7b9309c589

**Comment by carlescufi** [comment]
@Mani-Sadhasivam thanks for the insight. Do you have a PR in the main zephyr tree that references this one?

**Comment by carlescufi** [comment]
> @Mani-Sadhasivam thanks for the insight. Do you have a PR in the main zephyr tree that references this one?

Never mind, found it.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
