### PR TITLE
Update LoRaMac-Node to 4.4.5

### PR DESCRIPTION
**Pull request by adityaxavier**
Verified with IN865 with SX1262.

### CODE REVIEW

**Comment by adityaxavier** [comment]
@Mani-Sadhasivam There seems to be an issue with Sending Confirmed messages.. 
I am assuming this would require some changes from subsys/lorawan.c
Testing it.

**Comment by adityaxavier** [comment]
@Mani-Sadhasivam Found the issue to be due to CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE value.. It needs to be increased in the application layer. Once I increased it, its no longer crashing.
Please test and let me know.

**Comment by MaureenHelm** [comment]
Is there a corresponding PR to the main zephyr repo?

**Comment by adityaxavier** [comment]
> Is there a corresponding PR to the main zephyr repo?

I believe, that change would be needed when we bring in lora downlink receiver implementation. Not sure if its needed just for change in LoRaMac Node

**Comment by adityaxavier** [comment]
@Mani-Sadhasivam Do let me know if you need me to make any changes to this PR.

**Comment by carlescufi** [comment]
> > Is there a corresponding PR to the main zephyr repo?
> 
> I believe, that change would be needed when we bring in lora downlink receiver implementation. Not sure if its needed just for change in LoRaMac Node

@adityaxavier we need a PR in the main tree with a manifest update in order to merge the PR in the module repository. So I suggest you send that PR to the main tree or close this one, and reopen it when the receiver implementation you mention is added. cc @Mani-Sadhasivam

**Comment by tagunil** [comment]
Wouldn't it be better to update LoRaMac-node to recently released v4.5.1?

**Comment by carlescufi** [comment]
> Wouldn't it be better to update LoRaMac-node to recently released v4.5.1?

Yes, I agree. @adityaxavier would you please update the revision?

**Comment by adityaxavier** [comment]
> > Wouldn't it be better to update LoRaMac-node to recently released v4.5.1?
> 
> Yes, I agree. @adityaxavier would you please update the revision?

LoRaMac-Node 4.5.1 requires significant changes from the zephyr lora drivers side I believe. If need be I can update this to v4.4.7 as that is the latest which is still compatible with the current zephyr driver apis. 

However, 4.4.5 was the latest when I pushed the commit.

**Comment by tagunil** [comment]
I think I could try and port Zephyr side to LoRaMac-node v4.5.x, but there is another question: how exactly should this fork be updated? By merging the latest upstream on top of it? Is there a better way? What's the policy? @carlescufi @Mani-Sadhasivam

**Comment by carlescufi** [comment]
> I think I could try and port Zephyr side to LoRaMac-node v4.5.x, but there is another question: how exactly should this fork be updated? By merging the latest upstream on top of it? Is there a better way? What's the policy? @carlescufi @Mani-Sadhasivam

You can find the details in the link below. The maintainer of this module repo (@Mani-Sadhasivam) should weigh in on which method to use.
https://docs.zephyrproject.org/latest/guides/modules.html#synchronizing-with-upstream

**Comment by Mani-Sadhasivam** [comment]
> > I think I could try and port Zephyr side to LoRaMac-node v4.5.x, but there is another question: how exactly should this fork be updated? By merging the latest upstream on top of it? Is there a better way? What's the policy? @carlescufi @Mani-Sadhasivam
> 
> You can find the details in the link below. The maintainer of this module repo (@Mani-Sadhasivam) should weigh in on which method to use.

Sorry for jumping in very late. Got held up with official work. The rationale is to base zephyr fork on a latest stable branch (non rc) of upstream loramac-node repo. So for this discussion, I'm happy to accept PRs which updates zephyr fork to whatever latest stable branch without breaking the zephyr lora/lorawan support.

**Comment by liquiddandruff** [comment]
Looking forward to seeing this synced with upstream.

If I get difficulties with  v4.4.3 of loracmac-node I'll look to integrating this with upstream v4.5.2 (or v4.4.7 if easier).

**Comment by carlescufi** [comment]
@Mani-Sadhasivam please create a PR to the main zephyr tree updating the revision to the head of this PR

**Comment by Averosiation** [comment]
Hello Guys.
I want to implement LoraWan on **_STM32 NucleoL073_**, how can I implement this via Zephyr do you have any guideline, I am using Windows OS....
I do not  see difference between Loramac implementation and Loramac on Zephyr, may be I am wrong.

**Comment by Mani-Sadhasivam** [comment]
superseded by #9

**Pull request closed without merging**
